# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ebay-classifieds"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nik Petersen"]
  s.date = "2012-02-10"
  s.description = ""
  s.email = "demersus@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ebay-classifieds.gemspec",
    "lib/ebay-classifieds.rb",
    "lib/ebay_classifieds/api_connection.rb",
    "lib/ebay_classifieds/api_resource.rb",
    "lib/ebay_classifieds/ebay_classifieds.rb",
    "lib/ebay_classifieds/exceptions/http_error.rb",
    "lib/ebay_classifieds/models/ad.rb",
    "lib/ebay_classifieds/models/ad_address.rb",
    "lib/ebay_classifieds/models/attribute_initializer.rb",
    "lib/ebay_classifieds/models/category.rb",
    "lib/ebay_classifieds/models/picture.rb",
    "lib/ebay_classifieds/paginated_collection.rb",
    "spec/api_connection_spec.rb",
    "spec/api_resource_spec.rb",
    "spec/ebay_classifieds_spec.rb",
    "spec/fixtures/ad-12481583-many_pictures.xml",
    "spec/fixtures/ad-16722980-1_picture.xml",
    "spec/fixtures/ad-16723048-no_pictures.xml",
    "spec/fixtures/ads-empty.xml",
    "spec/fixtures/ads.xml",
    "spec/fixtures/categories.xml",
    "spec/fixtures/category-100012.xml",
    "spec/models/ad_address_spec.rb",
    "spec/models/ad_spec.rb",
    "spec/models/category_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/shared_api.rb",
    "spec/support/testing.rb"
  ]
  s.homepage = "http://github.com/demersus/ebay-classifieds"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "an ORM to interface with the ebay classifieds api"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<multi_xml>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rack>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<multi_xml>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<multi_xml>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

